steps:
steps:
  - name: node
    entrypoint: "bash"
    args:
      - "-c"
      - |
        npm install && npm test && npm run build

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - ${_SERVICE_NAME}
      - --gen2
      - --runtime=nodejs18
      - --trigger-http
      - --allow-unauthenticated
      - --region=${_REGION}
      - --entry-point=${_ENTRY_POINT}

substitutions:
  _SERVICE_NAME: hello-world
  _REGION: australia-southeast1
  _ENTRY_POINT: helloWorld